services:
  - type: web
    name: educlicker-nextjs
    runtime: image
    image:
      url: registry.hub.docker.com/lucasjjgg/educlicker-docker:latest
    envVars:
    - key: GITHUB_ID
      value: d94ef0b027b86b9883c9
    - key: GITHUB_SECRET
      sync: false
    - key: NEXTAUTH_URL
      sync: false
    - key: NEXTAUTH_SECRET
      sync: false
    - key: DATABASE_URL
      value: mongodb+srv://LuCaSjjgg:lucas@learningmongo.pfhsjsb.mongodb.net/educlicker


  - type: pserv
    name: educlicker-websocket
    runtime: image
    image: 
      url: registry.hub.docker.com/lucasjjgg/educlicker-websocket:latest