name: Docker Image CI

env:
  REGISTRY: registry.hub.docker.com

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: docker/build-push-action@v5.3.0

    - name: Authenticate on DockerHub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKERHUB_USER}} 
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    
    - name: Build and Push the Docker Image
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags:
          lucasjjgg/educlicker-docker:${{github.run_number}}
          lucasjjgg/educlicker-docker:latest
      


