name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v5.3.0

    - name: Authenticate on DockerHub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKERHUB_USER}} 
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    
    - name: Build and Push the Docker Image
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags:
          lucasjjgg/educlicker-docker:v1
          lucasjjgg/educlicker-docker:latest
      


